### PR TITLE
bump eks version in getting started guide

### PR DESCRIPTION
**Pull request by geoffcline**
**1. Issue, if available:**

**2. Description of changes:**
bump eks version in getting started guide

**3. Does this change impact docs?**
- [ X ] Yes, PR includes docs updates
- [ ] Yes, issue opened: *link to issue*
- [ ] No

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by njtran — APPROVED** [review]
LGTM. Thanks!

**Review by ellistarn — COMMENTED** [review]
How did you test this?

**Comment by geoffcline** [comment]
my current cluster was created with 1.21

**Review by bwagner5 — APPROVED** [review]
I have also used 1.21 w/ karpenter

**Pull request merged**
